# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20170929_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='is new'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='supplier url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='seo description'),
        ),
    ]
