# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20170929_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='show_in_store',
            field=models.BooleanField(default=False, verbose_name='show in store'),
        ),
    ]
