# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 14:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_productattribute_show_in_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=ckeditor.fields.RichTextField(default='<p></p>', verbose_name='Long description'),
        ),
    ]
