# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 08:29
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_bid_price',
            field=django_prices.models.PriceField(currency='VND', decimal_places=2, default=0, max_digits=12, verbose_name='Start bid price'),
        ),
    ]
