# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_start_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_related_products_+', to='product.Product'),
        ),
    ]
