# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 15:22
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_related_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_bid_price',
            field=django_prices.models.PriceField(currency='VND', decimal_places=2, default=Decimal('1000'), max_digits=12, verbose_name='Start bid price'),
        ),
    ]
