# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidsession',
            name='end_bid',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 6, 7, 12, 360902, tzinfo=utc), verbose_name='End bid time'),
        ),
    ]
