# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_auto_20171109_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidsession',
            name='end_bid',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 8, 57, 9, 924846, tzinfo=utc), verbose_name='End bid time'),
        ),
    ]
