# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 07:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_auto_20171111_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidsession',
            name='end_bid',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 8, 4, 47, 568606, tzinfo=utc), verbose_name='End bid time'),
        ),
    ]
