# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0011_auto_20171119_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidsession',
            name='end_bid',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 4, 28, 25, 230149, tzinfo=utc), verbose_name='End bid time'),
        ),
    ]
