# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0013_auto_20171119_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidsession',
            name='end_bid',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 17, 22, 46, 577899, tzinfo=utc), verbose_name='End bid time'),
        ),
    ]
