version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  search:
    image: elasticsearch:2.4
    ports:
      - '127.0.0.1:9200:9200'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://saleor:saleor@db/saleor
      - DEFAULT_FROM_EMAIL=noreply@example.com
      - ELASTICSEARCH_URL=http://search:9200/
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=True
      - LAZADA_API_KEY=ID5m9QghHJV5Xsdi7SJIOgVevtWk8mFr_SMfBIPdAj1pWxbCYLBPVKD8
      - LAZADA_USER_ID=sieuthitienich247.com@gmail.com
    depends_on:
      - db
      - redis
      - search
    ports:
      - "8000:8000"
    volumes:
      - .:/app:Z
      - ./static:/static
      - ./media:/media
