# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 03:10
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20171004_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='country'),
        ),
    ]
