# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 05:07
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170929_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='bid_price',
            field=django_prices.models.PriceField(blank=True, currency='VND', decimal_places=2, max_digits=12, null=True, verbose_name='bid price'),
        ),
    ]
