# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_product_start_bid_price'),
        ('cart', '0004_cartline_bid_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartline',
            unique_together=set([('cart', 'variant', 'data', 'bid_price')]),
        ),
    ]
