# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverygroup',
            name='shipping_price',
            field=django_prices.models.PriceField(currency='VND', decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='shipping price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=django_prices.models.PriceField(blank=True, currency='VND', decimal_places=2, max_digits=12, null=True, verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='vi', max_length=35),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_net',
            field=django_prices.models.PriceField(blank=True, currency='VND', decimal_places=2, max_digits=12, null=True, verbose_name='total net'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=django_prices.models.PriceField(blank=True, currency='VND', decimal_places=2, max_digits=12, null=True, verbose_name='total tax'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='content',
            field=models.CharField(max_length=250, verbose_name='content'),
        ),
    ]
