# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20170929_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleChanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Chanel name')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='lazada_order_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lazada order id'),
        ),
        migrations.AlterField(
            model_name='deliverygroup',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing'), ('ready_to_ship', 'Ready to ship'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('payment-pending', 'Payment pending'), ('fully-paid', 'Fully paid'), ('returned', 'Returned'), ('delivered', 'Delivered')], default='pending', max_length=32, verbose_name='delivery status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing'), ('ready_to_ship', 'Ready to ship'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('payment-pending', 'Payment pending'), ('fully-paid', 'Fully paid'), ('returned', 'Returned'), ('delivered', 'Delivered')], default='pending', max_length=32, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='orderhistoryentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing'), ('ready_to_ship', 'Ready to ship'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('payment-pending', 'Payment pending'), ('fully-paid', 'Fully paid'), ('returned', 'Returned'), ('delivered', 'Delivered')], max_length=32, verbose_name='order status'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_chanel',
            field=models.ForeignKey(blank=True, default='', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.SaleChanel'),
        ),
    ]
