# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20171119_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='delivery_group',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.DeliveryGroup', verbose_name='delivery group'),
        ),
    ]
