# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20171119_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='is printed'),
        ),
        migrations.AlterField(
            model_name='deliverygroup',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('ready_to_ship', 'Sẵn sàng giao hàng'), ('shipped', 'Đang giao hàng'), ('cancelled', 'Bị huỷ'), ('returned', 'Bị trả lại'), ('delivered', 'Giao hàng thành công.')], default='pending', max_length=32, verbose_name='delivery status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('ready_to_ship', 'Sẵn sàng giao hàng'), ('shipped', 'Đang giao hàng'), ('cancelled', 'Bị huỷ'), ('returned', 'Bị trả lại'), ('delivered', 'Giao hàng thành công.')], default='pending', max_length=32, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='orderhistoryentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('ready_to_ship', 'Sẵn sàng giao hàng'), ('shipped', 'Đang giao hàng'), ('cancelled', 'Bị huỷ'), ('returned', 'Bị trả lại'), ('delivered', 'Giao hàng thành công.')], max_length=32, verbose_name='order status'),
        ),
    ]
